### ISSUE TITLE
A feature called "Donate to insomnia (may cause some lag)" that is a btc miner but doesnt run without user consent

### ISSUE THREAD

**Issue by GreatZardasht** [yagel15637/PublicInsomnia#1]
A feature called "Donate to insomnia (may cause some lag)" that is a btc miner but doesnt run without user consent

**Comment by jndcmkxoikfjdcmxk** [comment]
no

**Comment by GreatZardasht** [comment]
yes

**Comment by yagel15637** [comment]
> no

@jndcmkxoikfjdcmxk why not? the client is open sourced and there's nothing we can hide.

**Comment by yagel15637** [comment]
closed to prevent further probably immature discussions.

**Comment by jndcmkxoikfjdcmxk** [comment]
ok

**Comment by GreatZardasht** [comment]
Ok, lmao
